### ISSUE TITLE
DUMP1090

### ISSUE THREAD

**Issue by khiles** [ShoGinn/planefinder#1]
is there a way to change DUMP1090_SERVER so it pointes to an ip address instead of looking for dump1090

see logs

==============================
======== Running with
==============================
- DUMP1090_SERVER=dump1090
- DUMP1090_PORT=30005
- PLANEFINDER_SHARECODE=REMOVED
- PLANEFINDER_LATITUDE =REMOVED
- PLANEFINDER_LONGITUDE=REMOVED
==============================

==============================
======== Building default config
==============================
==============================

==============================
======== Waiting for dump1090 to start up
==============================
==============================

==============================
======== Ping test to dump1090
==============================
ping: dump1090: No address associated with hostname

Where as ive put ip address in your  openskynetwork container and its followed ip and working fine so i dont know if this container does not support that or i have made an error possibly?

**Comment by ShoGinn** [comment]
Easy fix see https://github.com/ShoGinn/planefinder/commit/e7e4786b908135ea16da90522970d84ae6eb1f82

Basically pull the new image from docker hub and then add the environment variables:
```
DUMP1090_SERVER=your_server
DUMP1090_PORT=your_port
```
I recommend using the beast port of 30005
If this works please close the issue!

Have a good day

**Comment by hakan42** [comment]
Nice, could you add this to the other consuming images as well?

I am running my images with "--add-host dump1090:ip-of-my-dump-host", and putting that into environment variables would creating docker services much easier 😄

**Comment by ShoGinn** [comment]
Should be gtg now with the new variables
