### ISSUE TITLE
Image stops at "Starting pfclient"

### ISSUE THREAD

**Issue by hakan42** [ShoGinn/planefinder#2]
Starting the image, the last line(s) I am seeing is:

Jul 09 23:44:26 sunflower run.sh[11657]: ======== pfclient version
Jul 09 23:44:26 sunflower run.sh[11657]: ==============================
Jul 09 23:44:26 sunflower run.sh[11657]: 2019-07-09 21:44:26.179129 [-] PF Client version: 4.1.1
Jul 09 23:44:26 sunflower run.sh[11657]: ==============================
Jul 09 23:44:26 sunflower run.sh[11657]: ==============================
Jul 09 23:44:26 sunflower run.sh[11657]: ======== Starting pfclient
Jul 09 23:44:26 sunflower run.sh[11657]: ==============================

and then no further output. Also, the client is not available at port 30053. The port is free, no other process is blocking it.

Do you have any suggestions how I should continue debugging ?

**Comment by ShoGinn** [comment]
well I noticed that my readme didn't have the port specified for creation..
Now as for the not connecting.. not sure im running it now with no problems

**Comment by hakan42** [comment]
Works after "publishing" the port via "-p 30053:30053" as in the README

https://github.com/ShoGinn/planefinder/commit/175c87f77df1eee973259c82c19119403eb5e070
